package com.agentdock.model

data class AgentSession(
    var id: String = "",
    var projectId: String = "",
    var projectPath: String = "",
    var name: String = "",
    var providerId: String = "",
    var status: AgentSessionStatus = AgentSessionStatus.Restorable,
    var cwd: String = "",
    var providerSessionId: String? = null,
    var historyFilePath: String = "",
    var terminalTabId: String? = null,
    var summary: String = "",
    var linkedFiles: MutableList<String> = mutableListOf(),
    var createdAt: Long = 0L,
    var updatedAt: Long = 0L,
    var pinned: Boolean = false,
    var archived: Boolean = false,
    var lastError: String? = null,
    var tokenUsageCached: Boolean = false,
    var tokenUsageAvailable: Boolean = false,
    var tokenUsageTotal: Long = 0L,
    var tokenUsageDaily: MutableList<Long> = mutableListOf(),
    var tokenUsageSourcePath: String = "",
    var tokenUsageSourceModifiedAt: Long = 0L,
    var tokenUsageSourceLength: Long = 0L,
    var tokenUsageAnchorEpochDay: Long = 0L,
    var averageResponseTimeDailyMillis: MutableList<Long> = mutableListOf(),
    var sessionMetricsCacheVersion: Int = 0
)
